apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base
images:
- name: azman0101/docker-grafana-backup-tool
  newTag: latest-v3
- name: azman0101/s5cmd
  newTag: feat-support-env-var-advanced-v2

transformers:
  - annotations.yaml
  - annotations-irsa.yaml

secretGenerator:
- name: grafana-secrets
  envs:
  - .env.secret
  type: Opaque

configMapGenerator:
  - name: config-grafana-backup
    env: config.properties

